{{- if .Values.mcpGatewayExtension.create }}
apiVersion: mcp.kagenti.com/v1alpha1
kind: MCPGatewayExtension
metadata:
  name: {{ include "mcp-gateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mcp-gateway.labels" . | nindent 4 }}
  annotations:
    kuadrant.io/alpha-gateway-public-host: {{ .Values.gateway.publicHost | quote }}
    {{- if .Values.broker.pollInterval }}
    kuadrant.io/alpha-gateway-poll-interval: {{ .Values.broker.pollInterval | quote }}
    {{- end }}
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ .Values.mcpGatewayExtension.gatewayRef.name }}
    {{- if .Values.mcpGatewayExtension.gatewayRef.namespace }}
    namespace: {{ .Values.mcpGatewayExtension.gatewayRef.namespace }}
    {{- end }}
{{- end }}
