---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# broker-only deployment (controller is only in mcp-system)
namespace: mcp-second-instance

namePrefix: second-

resources:
  - ../../base
  - namespace.yaml

patches:
  # patch broker deployment with correct gateway host
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: mcp-broker-router
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: mcp-second.127-0-0-1.sslip.io

  # patch HTTPRoute with correct hostname and backend ref
  - target:
      group: gateway.networking.k8s.io
      version: v1
      kind: HTTPRoute
      name: mcp-route
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: mcp-second.127-0-0-1.sslip.io
      - op: replace
        path: /spec/rules/0/backendRefs/0/name
        value: second-mcp-broker
      - op: replace
        path: /spec/rules/1/backendRefs/0/name
        value: second-mcp-broker
