---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  labels:
    istio: ingressgateway
    gateway.io/name: e2e-1
  name: e2e-1
  namespace: gateway-system
spec:
  gatewayClassName: istio
  listeners:
    - name: mcp
      hostname: 'e2e-1.127-0-0-1.sslip.io'
      port: 8080
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: mcps
      port: 8080
      protocol: HTTP
      hostname: '*.e2e-1.mcp.local'
      allowedRoutes:
        namespaces:
          from: All
