---
apiVersion: v1
kind: Service
metadata:
  labels:
    gateway.istio.io/managed: istio.io-gateway-controller
    gateway.networking.k8s.io/gateway-name: e2e-1
    istio.io/dataplane-mode: none
  name: e2e-1-np
  namespace: gateway-system
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ports:
    - appProtocol: http
      name: mcp
      nodePort: 30472
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    gateway.networking.k8s.io/gateway-name: e2e-1
  sessionAffinity: None
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    gateway.istio.io/managed: istio.io-gateway-controller
    gateway.networking.k8s.io/gateway-name: e2e-2
    istio.io/dataplane-mode: none
  name: e2e-2-np
  namespace: gateway-system
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ports:
    - appProtocol: http
      name: mcp
      nodePort: 30471
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    gateway.networking.k8s.io/gateway-name: e2e-2
  sessionAffinity: None
  type: NodePort
