---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# broker-only resources (controller resources are in mcp-system overlay only)
resources:
  - rbac-broker.yaml
  - broker-service.yaml
  - mcpgatewayextension.yaml
  - deployment-broker.yaml
  - httproute.yaml
