apiVersion: mcp.kagenti.com/v1alpha1
kind: MCPGatewayExtension
metadata:
  name: mcp-gateway-extension
  annotations:
    kuadrant.io/alpha-gateway-public-host: "mcp.127-0-0-1.sslip.io:8001"
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: mcp-gateway
    namespace: gateway-system
