---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mcp.kagenti.com_mcpgatewayextensions.yaml
  - mcp.kagenti.com_mcpserverregistrations.yaml
  - mcp.kagenti.com_mcpvirtualservers.yaml
  - mcp.kagenti.com_mcpgatewayextensions.yaml
